{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  labels:
    app: clickhouse-config
data:
  zookeeper.xml: |-
    <yandex>
      <zookeeper incl="zookeeper-servers">
      {{range $i, $zk := until (atoi (printf "%d" (int64 .Values.zookeeper.replicaCount))) }}
        <node>
            <host>zk-{{$i}}.zk.{{ $root.Values.clusterDNS }}</host>
            <port>2181</port>
        </node>
      {{end}}
      </zookeeper>
    </yandex>
