{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-configd
  labels:
    app: clickhouse-configd
data:
  remote_servers.xml: |-
    <yandex>
      <remote_servers incl="clickhouse_remote_servers">
        <clicks_cluster>
          <shard>
            <internal_replication>true</internal_replication>
            {{range $i, $e := until (atoi (printf "%d" (int64 .Values.clickhouse.replicaCount))) }}
            <replica>
                <default_database>default</default_database>
                <host>clickhouse-{{$i}}.clickhouse.{{ $root.Values.clusterDNS }}</host>
                <port>9000</port>
            </replica>
            {{end}}
          </shard>
        </clicks_cluster>
      </remote_servers>
    </yandex>
  zookeeper.xml: |-
    <yandex>
      <zookeeper incl="zookeeper-servers">
      {{range $i, $zk := until (atoi (printf "%d" (int64 .Values.zookeeper.replicaCount))) }}
        <node>
            <host>zk-{{$i}}.zk.{{ $root.Values.clusterDNS }}</host>
            <port>2181</port>
        </node>
      {{end}}
      </zookeeper>
    </yandex>
  users.xml: |-
    <yandex>
      <profiles>
        <writer>
          <max_memory_usage>10000000000</max_memory_usage>
          <use_uncompressed_cache>0</use_uncompressed_cache>
          <load_balancing>random</load_balancing>
        </writer>
        <reader>
          <max_memory_usage>10000000000</max_memory_usage>
          <use_uncompressed_cache>0</use_uncompressed_cache>
          <load_balancing>random</load_balancing>
          <readonly>1</readonly>
        </reader>
      </profiles>
      <users>
        <writer>
          <password>{{ .Values.clickhouse.writerPass }}</password>
          <profile>writer</profile>
          <quota>default</quota>
          <networks>
            <ip>::/0</ip>
          </networks>
        </writer>
        <reader>
          <password>{{ .Values.clickhouse.readerPass }}</password>
          <profile>reader</profile>
          <quota>default</quota>
          <allow_databases>
            <database>default</database>
            <database>system</database>
          </allow_databases>
          <networks>
            <ip>::/0</ip>
          </networks>
        </reader>
      </users>
      <quotas>
        <default>
          <interval>
            <duration>3600</duration>
            <queries>0</queries>
            <errors>0</errors>
            <result_rows>0</result_rows>
            <read_rows>0</read_rows>
            <execution_time>0</execution_time>
          </interval>
        </default>
      </quotas>
    </yandex>
